package dashboard

import (
	"context"
	json "encoding/json/v2"
	"fmt"
	"net/http"
	"regexp"
	"sort"
	"strings"

	"9router/proxy/internal/handlerutil"
	"9router/proxy/internal/providers"
)

// autoFamilyComboKind marks combos generated by HandleAutoFamilyCombos. Unlike
// the locked auto free-tier combo these stay editable: they are a starting
// point, not registry truth, so the user can prune or reorder them freely.
const autoFamilyComboKind = "auto-family"

// minFamilyMembers is the cutoff below which a family is not worth a combo: a
// family with a single usable model has nothing to fall back to.
const minFamilyMembers = 2

// HandleAutoFamilyCombos handles POST /api/combos/auto-family.
//
// Groups every usable LLM model of connected providers by normalized family
// (so "claude-sonnet-4.6" and "claude-sonnet-4.5" land together, as do the same
// model across providers) and upserts one fallback combo per family. A model is
// usable when its provider has a connection and the user has not disabled it.
func (h *DashboardHandler) HandleAutoFamilyCombos(w http.ResponseWriter, r *http.Request) {
	groups, err := h.usableModelFamilies(r.Context())
	if err != nil {
		handlerutil.WriteJSONError(w, http.StatusInternalServerError, err.Error())
		return
	}

	created := make([]string, 0, len(groups))
	for family, members := range groups {
		if len(members) < minFamilyMembers {
			continue
		}
		modelsJSON, err := json.Marshal(members)
		if err != nil {
			handlerutil.WriteJSONError(w, http.StatusInternalServerError, "failed to encode models")
			return
		}
		id := autoFamilyComboID(family)
		name := "Auto: " + family
		existing, err := h.Repo.GetComboById(id)
		if err != nil {
			handlerutil.WriteJSONError(w, http.StatusInternalServerError, err.Error())
			return
		}
		if existing == nil {
			if err := h.Repo.CreateCombo(id, name, autoFamilyComboKind, string(modelsJSON), "fallback"); err != nil {
				handlerutil.WriteJSONError(w, http.StatusInternalServerError, err.Error())
				return
			}
		} else if err := h.Repo.UpdateCombo(id, name, autoFamilyComboKind, string(modelsJSON), "fallback"); err != nil {
			handlerutil.WriteJSONError(w, http.StatusInternalServerError, err.Error())
			return
		}
		created = append(created, family)
	}
	sort.Strings(created)

	handlerutil.WriteJSON(w, http.StatusOK, map[string]any{
		"status":  "ok",
		"created": created,
		"count":   len(created),
	})
}

// usableModelFamilies maps a normalized family to every usable "alias/model"
// id belonging to it, across all providers with an active connection.
func (h *DashboardHandler) usableModelFamilies(ctx context.Context) (map[string][]string, error) {
	conns, err := h.Repo.GetProviderConnections("", true)
	if err != nil {
		return nil, fmt.Errorf("usableModelFamilies: list connections: %w", err)
	}
	active := make(map[string]struct{}, len(conns))
	for _, c := range conns {
		active[c.Provider] = struct{}{}
	}
	disabled, err := h.disabledModelsByAlias()
	if err != nil {
		return nil, fmt.Errorf("usableModelFamilies: disabled models: %w", err)
	}
	custom, err := h.customLLMModels()
	if err != nil {
		return nil, fmt.Errorf("usableModelFamilies: custom models: %w", err)
	}

	groups := make(map[string][]string)
	for providerID := range active {
		alias := providers.GetProviderAlias(providerID)
		for _, modelID := range providers.GetProviderModels(providerID) {
			if !isUsableChatModel(providerID, modelID, disabled[alias]) {
				continue
			}
			key := alias + "/" + modelID
			family := modelFamily(modelID)
			groups[family] = appendUnique(groups[family], key)
		}
	}
	// Custom models are first-class: a model the user added for a provider joins
	// its family too, so a hand-added gateway model can backstop the catalog.
	for _, key := range custom {
		alias, model := splitAliasModel(key)
		groups[modelFamily(model)] = appendUnique(groups[modelFamily(model)], alias+"/"+model)
	}

	for family := range groups {
		sort.Strings(groups[family])
	}
	return groups, nil
}

// isUsableChatModel reports whether alias/provider exposes modelID as a chat
// model the user has not turned off. Embedding, image and audio models are
// excluded: they cannot serve a chat fallback chain.
func isUsableChatModel(providerID, modelID string, disabled map[string]struct{}) bool {
	if providers.GetProviderModelKind(providerID, modelID) != "" {
		return false
	}
	if isEmbeddingModel(modelID) {
		return false
	}
	if _, off := disabled[modelID]; off {
		return false
	}
	return true
}

// isEmbeddingModel catches the chat-shaped embedding ids some catalogs list
// without a kind, e.g. "text-embedding-3-small" or "gemini-embedding-001".
func isEmbeddingModel(modelID string) bool {
	m := strings.ToLower(modelID)
	return strings.Contains(m, "embedding")
}

// versionToken matches a generation marker: "4.6", "3.1", "2", "v2.5".
var versionToken = regexp.MustCompile(`^v?\d+(\.\d+)*$`)

// letterDigitToken matches a mid-name generation marker such as kimi-"k2.6" or
// minimax-"m3". It is only stripped when it is not the first token: a leading
// token is the model line itself, so "o1" and "o3-mini" survive intact.
var letterDigitToken = regexp.MustCompile(`^[a-z]\d+(\.\d+)*$`)

// familyFlagWords are capability/lifecycle markers, not identity: stripping
// them lets "gemini-3.1-flash-preview" and "gemini-3-flash-preview" meet in the
// family "gemini-flash".
var familyFlagWords = map[string]bool{
	"preview": true, "exp": true, "experimental": true,
	"beta": true, "latest": true, "free": true, "auto": true,
}

// appendUnique adds id only when it is not already in members, so the same
// model reaching a family via the catalog and a custom entry is not listed twice.
func appendUnique(members []string, id string) []string {
	for _, m := range members {
		if m == id {
			return members
		}
	}
	return append(members, id)
}

// splitAliasModel splits a stored "alias/model" id, tolerating ids that carry
// no alias at all.
func splitAliasModel(aliasModel string) (alias, model string) {
	slash := strings.LastIndex(aliasModel, "/")
	if slash < 0 {
		return "", aliasModel
	}
	return aliasModel[:slash], aliasModel[slash+1:]
}

// modelFamily collapses a model id to the family every version of that model
// shares, across providers. Tokens that are generation numbers or lifecycle
// flags are dropped; size and role words (sonnet, opus, mini, flash, pro,
// codex...) are kept, so "claude-sonnet-4.6" from cc and "claude-sonnet-4.5"
// from claude both become "claude-sonnet" and land in one combo.
func modelFamily(modelID string) string {
	lower := strings.ToLower(modelID)

	// Drop a free-tier marker ("model:free") so free and paid versions group.
	lower = strings.TrimSuffix(lower, ":free")

	parts := strings.Split(lower, "-")
	kept := make([]string, 0, len(parts))
	for i, p := range parts {
		if p == "" {
			continue
		}
		if versionToken.MatchString(p) || familyFlagWords[p] {
			continue
		}
		if i > 0 && letterDigitToken.MatchString(p) {
			continue
		}
		kept = append(kept, p)
	}
	if len(kept) == 0 {
		// Nothing identifiable (e.g. a pure version id); keep the original so
		// the model is not silently merged into an empty family.
		return lower
	}
	return strings.Join(kept, "-")
}

// autoFamilyComboID is the stable id of one family's generated combo, so
// regenerating refreshes the same row instead of stacking duplicates.
func autoFamilyComboID(family string) string {
	safe := strings.NewReplacer("/", "-", ":", "-", " ", "-").Replace(family)
	return autoFamilyComboKind + "-" + safe
}

// disabledModelsByAlias loads the disabledModels kv scope and decodes each
// provider's model list into a set for fast lookup.
func (h *DashboardHandler) disabledModelsByAlias() (map[string]map[string]struct{}, error) {
	kv, err := h.Repo.GetKVScope("disabledModels")
	if err != nil {
		return nil, err
	}
	out := make(map[string]map[string]struct{}, len(kv))
	for alias, raw := range kv {
		var arr []string
		if err := json.Unmarshal([]byte(raw), &arr); err != nil {
			// Some rows store a bare scalar; treat as a single entry.
			out[alias] = map[string]struct{}{raw: {}}
			continue
		}
		set := make(map[string]struct{}, len(arr))
		for _, m := range arr {
			set[m] = struct{}{}
		}
		out[alias] = set
	}
	return out, nil
}

// customLLMModels returns the "alias/model" ids of the user's saved custom
// chat models, so hand-added models participate in family grouping.
func (h *DashboardHandler) customLLMModels() ([]string, error) {
	kv, err := h.Repo.GetKVScope("customModels")
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(kv))
	for key, raw := range kv {
		// Key shape is "alias|model|type".
		parts := strings.Split(key, "|")
		if len(parts) < 3 || parts[2] != "llm" {
			continue
		}
		var entry struct {
			ProviderAlias string `json:"providerAlias"`
			ID            string `json:"id"`
		}
		if err := json.Unmarshal([]byte(raw), &entry); err == nil && entry.ID != "" {
			alias := entry.ProviderAlias
			if alias == "" {
				alias = parts[0]
			}
			out = append(out, alias+"/"+entry.ID)
			continue
		}
		if parts[0] != "" && parts[1] != "" {
			out = append(out, parts[0]+"/"+parts[1])
		}
	}
	sort.Strings(out)
	return out, nil
}
